# Generated by Django 6.0.6 on 2026-07-14 10:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active_record', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50)),
                ('section', models.CharField(max_length=10)),
                ('academic_year', models.CharField(max_length=20)),
                ('class_code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
            ],
            options={
                'unique_together': {('name', 'section', 'academic_year')},
            },
        ),
    ]
