# Generated by Django 6.0.6 on 2026-07-14 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='batch_name',
            field=models.CharField(default=11, help_text='e.g., Batch 2026, Group A', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='class',
            name='join_code',
            field=models.CharField(blank=True, help_text='Short code for students to join (e.g., A1B2C3). Auto-generated if empty.', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
