# Generated by Django 6.0.6 on 2026-07-14 13:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_class_batch_name_class_join_code_alter_class_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='join_code',
        ),
        migrations.AlterField(
            model_name='class',
            name='academic_year',
            field=models.CharField(help_text='e.g., 2026', max_length=20),
        ),
        migrations.AlterField(
            model_name='class',
            name='class_code',
            field=models.CharField(blank=True, help_text='Auto-generated code for students to join this batch.', max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.CharField(help_text='e.g., 1st Sem, Class 10', max_length=100),
        ),
        migrations.AlterField(
            model_name='class',
            name='section',
            field=models.CharField(help_text='e.g., A, B', max_length=10),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active_record', models.BooleanField(default=True)),
                ('name', models.CharField(help_text='e.g., Mathematics, Physics', max_length=100)),
                ('code', models.CharField(help_text='e.g., MATH101', max_length=20, unique=True)),
                ('full_marks', models.IntegerField(default=100)),
                ('pass_marks', models.IntegerField(default=40)),
                ('class_obj', models.ForeignKey(help_text='Which batch/class is this subject taught to?', on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='system.class')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
