# Generated by Django 6.0.6 on 2026-07-21 15:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_enrollment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active_record', models.BooleanField(default=True)),
                ('exam_type', models.CharField(choices=[('Midterm', 'Midterm Exam'), ('Final', 'Final Exam'), ('Assignment', 'Assignment'), ('Quiz', 'Quiz'), ('Practical', 'Practical')], max_length=20)),
                ('obtained_marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('letter_grade', models.CharField(blank=True, max_length=2)),
                ('is_passed', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='grades', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='system.subject')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_grades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Grade',
                'verbose_name_plural': 'Grades',
                'ordering': ['-created_at'],
                'unique_together': {('student', 'subject', 'exam_type')},
            },
        ),
    ]
