# Generated by Django 6.0.6 on 2026-07-22 16:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_grade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='teachers',
            field=models.ManyToManyField(blank=True, help_text='Select the teacher(s) assigned to teach this subject.', limit_choices_to={'role': 'teacher'}, related_name='taught_subjects', to=settings.AUTH_USER_MODEL),
        ),
    ]
